name: dayaheadprice
services:
  # Day Ahead Price web app
  dayaheadprice:
    container_name: dayaheadprice
    hostname: dayaheadprice
    image: dayaheadprice:latest
    environment:
      ASPNETCORE_ENVIRONMENT: Release
      EndpointOptions__ApiKey: "${ENTSOE_APIKEY:?err}"
      TZ: "Europe/Helsinki"
    ports:
      - 127.0.0.1:8548:8080
    volumes:
      - dayaheadprice-dpkeys:/app/dpkeys
    networks:
      - dayaheadpricenet
    restart: on-failure
    logging:
      driver: k8s-file
      options:
        path: /var/log/containers/dayaheadprice.log
        max-size: 4mb

networks:
  dayaheadpricenet:

volumes:
  dayaheadprice-dpkeys:
